CREATE TABLE IF NOT EXISTS `a_comments_messages` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL,
  `DATE_CREATE` datetime NOT NULL,
  `MESSAGE` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `a_comments_users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` varchar(50) NOT NULL,
  `LASTNAME` varchar(50) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PHOTO` int(11) NOT NULL,
  `SOCIAL_ID` int(11) NOT NULL,
  `SOCIAL_PROVIDER` varchar(50) NOT NULL,
  `SOCIAL_PROFILE_URL` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `a_comments_vote` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VOTE` enum('LIKE','DISLIKE') NOT NULL,
  `MESSAGE_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;